### ISSUE TITLE
club monaco link shouldn't be mobile

### ISSUE THREAD

**Issue by whereismyhat** [bizweekgraphics/back-to-school-gift-guide#1]
Should be this instead: http://www.clubmonaco.com/product/index.jsp?productId=58716506

**Comment by tophtucker** [comment]
HELL YEA @whereismyhat WELCOME TO THE PARTY

**Comment by whereismyhat** [comment]
YEAHHHHH
![samoyed bimbo fall](https://cloud.githubusercontent.com/assets/6108336/9066987/b600f64c-3aa8-11e5-902a-920943e5ed52.gif)
